### ISSUE TITLE
import ledger using `canister:ledger` syntax

### ISSUE THREAD

**Issue by letmejustputthishere** [flowerpowerdao/power-equalizer#43]

**Comment by ZenVoich** [comment]
Should it work?
![image](https://user-images.githubusercontent.com/21315978/227206744-d666e7bd-d570-40fc-af52-25fa8412845c.png)

**Comment by letmejustputthishere** [comment]
yes, try deploying the canister and the error should disappear

**Comment by ZenVoich** [comment]
Deploy works, but in vscode error remains. Probably related to https://github.com/dfinity/vscode-motoko/issues/186
