### ISSUE TITLE
sale refund bug

### ISSUE THREAD

**Issue by letmejustputthishere** [flowerpowerdao/power-equalizer#49]
we have a user that transferred ICP to our subaccounts twice, but  since then they are stuck
https://icscan.io/account/58f2889cee574000606a9f9401ced0583bd7f5f8528177010591e4e12a18ad49
https://icscan.io/account/415ec833dedbf201ab16bd5c050bf2d6f94d200c52ec65caa2570be175602bb0

i verified the addresses, and those are indeed account identifiers that belong to our canister and were given out during the sale.
we have to investigate why those failed sales weren't refunded until now.

this was the error he saw while minting
![telegram-cloud-photo-size-1-5181640067532303032-y](https://user-images.githubusercontent.com/32162112/221637014-efe87547-b200-4427-8d8c-045850e0b6c2.jpg)
 > cloudedlogic, [27. Feb 2023 at 18:25:05]:
He was telling me that initially his stoic was on his phone
So he was importing private keys to his laptops in order to mint
If that has any potentially effect

**Comment by ZenVoich** [comment]
@letmejustputthishere  We should refund that stuck icps, right? Do you want me to add that logic?

**Comment by letmejustputthishere** [comment]
how would you do that? i wouldn't want to add any admin access method for it 🤔 
and don't you think that through the new logic in the minting page this issue won't happen?

**Comment by ZenVoich** [comment]
> how would you do that?

maybe add just one method with hardcoded those 2 addresses?
Add method. Upgrade. Call to refund. Remove method. Upgrade again.
This will require to use legacy  `dfx_send` I suppose 🤔

> and don't you think that through the new logic in the minting page this issue won't happen?

Yes, it shouldn't.

If that user is fine with stuck funds we can leave it as is)
